print("Hello World")
print("21*3")
print(135.682)
print("pi =", 3.141)
print("pi = 3.141")
print("She explained, \"Mae fy something something.\"")
print("Here is a backslash: \\")
print(False)
type(False)
type("False")
type(4)